version: 2.1

jobs:
  test:
    docker:
      - image: ayazhafiz/skittles
    steps:
      - checkout
      - run: eval $(opam env) && dune test
  publish_site:
    docker:
      - image: ayazhafiz/skittles
    steps:
      - checkout
      - run: |
          eval $(opam env)
          ./scripts/site.sh build-all
          ./scripts/site.sh copy-out /tmp/out
      - run: |
          git reset --hard HEAD
          git config --global user.email "builds@circleci.com"
          git config --global user.name "CircleCI"
          git remote add circleorigin https://${GH_TOKEN}@github.com/ayazhafiz/skittles
          git checkout gh-pages
          rm -rf *
          cp -v -a /tmp/out/. .
          git add -f .
          if git commit -m "CircleCI build $CIRCLE_BUILD_NUM" ; then
            git push -fq circleorigin
            echo -e "Deploy completed\n"
          else
            echo -e "Content not changed, nothing to deploy\n"
          fi          

workflows:
  test_and_publish:
    jobs:
      - test
      - publish_site:
          requires:
            - test
          filters:
            branches:
              only: [ base ]
