version: 2.1

jobs:
  test:
    docker:
      - image: ayazhafiz/skittles
    steps:
      - checkout
      - run: |
          eval $(opam env)
          source env.sh
          dune test
  publish_site:
    docker:
      - image: ayazhafiz/skittles
    steps:
      - checkout
      - restore_cache:
          keys:
            - gatsby
      - restore_cache:
          keys:
            - node_modules-{{ checksum "yarn.lock" }}
      - run:
          name: Build site
          command: |
            eval $(opam env)
            source env.sh
            dune build
            yarn install
            cd www && yarn build
            cp -R public /tmp/out && cd ..
          no_output_timeout: 20m
          environment:
            GATSBY_CPU_COUNT: 2
            NODE_OPTIONS: "--max_old_space_size=8192"
      - save_cache:
          key: gatsby
          paths:
            www/.cache
            www/public
      - save_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            node_modules
      - run: |
          git reset --hard HEAD
          git config --global user.email "builds@circleci.com"
          git config --global user.name "CircleCI"
          git remote add circleorigin https://${GH_TOKEN}@github.com/ayazhafiz/skittles
          git checkout gh-pages
          rm -rf * .yarn .cache
          cp -v -a /tmp/out/. .
          git add -f .
          if git commit -m "CircleCI build $CIRCLE_BUILD_NUM" ; then
            git push -fq circleorigin
            echo -e "Deploy completed\n"
          else
            echo -e "Content not changed, nothing to deploy\n"
          fi          

workflows:
  test_and_publish:
    jobs:
      - test
      - publish_site:
          requires:
            - test
          filters:
            branches:
              only: [ base ]
