#!/bin/bash

EXE="with_references"

ROOT="$(git rev-parse --show-toplevel)"
EXEC_PATH="$(realpath --relative-to="$ROOT" $(pwd))/$EXE.exe"

dune build >/dev/null 2>&1
cd "$ROOT"
dune exec "$EXEC_PATH" $@
