#!/bin/bash

INPUT="$(pwd)/test.input"
GOLDEN="$(pwd)/test.golden"
REAL="$(pwd)/test.real"

if [ "$1" = "-u" ]; then
  ./run "$INPUT" > "$REAL"
  cp "$REAL" "$GOLDEN"
elif [ "$1" = "-d" ]; then
  ./run "$INPUT" > "$REAL"
  diff --color "$GOLDEN" "$REAL"
else
 ./run "$INPUT"
fi
